# Generated by Django 5.2.10 on 2026-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='normal', max_length=20),
            preserve_default=False,
        ),
    ]
