# Generated by Django 5.2.10 on 2026-03-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_package_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stay_plan',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
