# Generated by Django 5.2.10 on 2026-03-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_package_stay_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='original_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
