# Generated by Django 5.2.10 on 2026-03-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_package_discount_percent_package_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rehion',
            field=models.CharField(choices=[('north', 'North India'), ('west', 'West India'), ('south', 'South India'), ('northeast', 'North-East India')], default='north', max_length=20),
        ),
    ]
