# Generated by Django 5.2.10 on 2026-03-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_package_rehion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='rehion',
            new_name='region',
        ),
    ]
