# Generated by Django 5.2.10 on 2026-03-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_rename_rehion_package_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_trending',
            field=models.BooleanField(default=True),
        ),
    ]
