# Generated by Django 5.2.10 on 2026-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_package_is_trending_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='region_international',
            field=models.CharField(blank=True, choices=[('europe', 'Europe'), ('southeast_asia', 'Southeast Asia'), ('middle_east', 'Middle East'), ('maldives', 'Maldives'), ('usa', 'USA'), ('dubai', 'Dubai')], max_length=50, null=True),
        ),
    ]
