# Generated by Django 5.2.10 on 2026-03-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_package_region_international'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='region',
            field=models.CharField(blank=True, choices=[('north', 'North India'), ('west', 'West India'), ('south', 'South India'), ('northeast', 'North-East India')], max_length=20, null=True),
        ),
    ]
