# Generated by Django 5.2.10 on 2026-03-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_package_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='exclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='inclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(),
        ),
    ]
