# Generated by Django 5.2.10 on 2026-03-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_packageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights_list', to='travel.package')),
            ],
        ),
    ]
