# Generated by Django 5.2.10 on 2026-03-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_itineraryday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='package',
            name='inclusions',
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions_list', to='travel.package')),
            ],
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions_list', to='travel.package')),
            ],
        ),
    ]
