# Generated by Django 5.2.10 on 2026-03-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_remove_package_exclusions_remove_package_inclusions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cancellation_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='confirmation_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='refund_policy',
            field=models.TextField(blank=True),
        ),
    ]
