# Generated by Django 5.2.10 on 2026-03-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_package_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='cancellation_policy',
            field=models.TextField(default='Free cancellation up to 7 days before travel date. 50% cancellation charges between 3–7 days before travel. No refund for cancellations within 48 hours of departure. No-show bookings are non-refundable.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='confirmation_policy',
            field=models.TextField(default='Booking confirmation is subject to availability at the time of reservation. A confirmation voucher will be shared within 24 hours of successful payment.In case of non-availability, an alternative option of similar category will be provided.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='payment_policy',
            field=models.TextField(default='A minimum of 30% advance payment is required to confirm the booking. Full payment must be completed before the start of the trip. Payments can be made via UPI, bank transfer, or online payment gateway.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='refund_policy',
            field=models.TextField(default='Refunds (if applicable) will be processed within 7–10 working days. Transaction charges or gateway fees may be deducted. No refund will be provided for partially utilized services.'),
        ),
    ]
