# Generated by Django 5.2.10 on 2026-04-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_booking_created_at_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
